/*
 * Copyright (c) 2021-present unTill Pro, Ltd.
 */

// auto generated by airs-importbo. DO NOT EDIT.

const ForeignKeys = {
	"currency_notes_coins": {
		"id_currency": "currency",
		"id_notes_coins": "notes_coins"
	},
	"pos_emails": {},
	"orders": {
		"id_untill_users": "untill_users",
		"id_sales_area": "sales_area",
		"id_table_area": "table_area"
	},
	"oi_onhold_logoff": {
		"id_order_item": "order_item"
	},
	"eft_config_sel_items": {
		"id_eft_config_selections": "eft_config_selections"
	},
	"order_coupon_items": {
		"id_order_item": "order_item",
		"id_coupon_item": "coupon_items"
	},
	"pbill_payments_bookp": {
		"id_pbill_payments": "pbill_payments",
		"id_bookkeeping": "bookkeeping"
	},
	"accounts_payments": {
		"id_untill_users": "untill_users",
		"id_clients": "clients",
		"id_sales_area": "sales_area",
		"id_pbill_payments": "pbill_payments"
	},
	"department_articles": {
		"id_articles": "articles",
		"id_department": "department"
	},
	"vd_groups": {},
	"inventory_item": {
		"id_unity": "unity",
		"id_inventory_categories": "inventory_categories",
		"id_count_frequencies": "count_frequencies",
		"id_recipe": "recipe"
	},
	"beco_groups": {},
	"stock_doc": {
		"id_orders": "orders",
		"id_pbill": "pbill",
		"id_stock_invoice": "stock_invoice",
		"id_stock_adjustment": "stock_adjustment",
		"id_stock_cost_correction": "stock_cost_correction"
	},
	"keys": {},
	"falcon_screens": {
		"id_screen_groups": "screen_groups"
	},
	"smartcard_groups": {
		"id_prices": "prices",
		"id_payments": "payments"
	},
	"untill_user_wages": {
		"id_untill_users": "untill_users",
		"id_waiter_positions": "waiter_positions"
	},
	"coupon_templates": {
		"id_options": "options",
		"id_prices": "prices"
	},
	"stock_adjustment": {
		"id_untill_users": "untill_users",
		"id_transfer_to": "stock_units",
		"id_stock_locations": "stocking_locations",
		"id_stock_locations_to": "stocking_locations",
		"id_conduct_untill_user": "untill_users",
		"id_spc": "stock_physical_count"
	},
	"screens": {
		"id_screen_groups": "screen_groups"
	},
	"coupons": {
		"id_untill_users": "untill_users",
		"id_coupon_templates": "coupon_templates",
		"id_articles": "articles"
	},
	"bo_bookmarks": {},
	"ta_ks_notify": {
		"id_ks": "kitchen_screens",
		"id_table_printer": "table_printer"
	},
	"periods": {},
	"neg_pbill": {
		"id_pbill": "pbill",
		"id_pbill_close": "pbill"
	},
	"untill_users": {
		"id_countries": "countries",
		"id_group_users": "untill_group_users"
	},
	"article_options_defaults": {
		"id_article_options": "article_options",
		"id_option_article": "option_article"
	},
	"db_tasks_recipients": {
		"id_db_tasks": "db_tasks"
	},
	"pua_groups_articles": {
		"id_pua_groups": "pua_groups",
		"id_articles": "articles"
	},
	"report_group_tickets": {
		"id_tickets": "tickets",
		"id_report_groups": "report_groups"
	},
	"break_reasons": {},
	"article_garbagecol": {
		"id_articles": "articles"
	},
	"blacklist": {
		"id_clients": "clients"
	},
	"count_frequencies": {},
	"stock_physical_count": {
		"id_count_frequencies": "count_frequencies",
		"id_stock_locations": "stocking_locations",
		"id_conduct_untill_user": "untill_users"
	},
	"option_article": {
		"id_articles": "articles",
		"id_options": "options"
	},
	"screen_groups": {},
	"article_bonus_prices": {
		"id_prices": "prices",
		"id_article_bonus_groups": "article_bonus_groups",
		"id_currency": "currency"
	},
	"drawer_payments": {
		"id_payments": "payments",
		"id_drawers": "printers"
	},
	"caller_groups": {},
	"pbill_item": {
		"id_articles": "articles",
		"id_courses": "courses",
		"id_option_article": "option_article",
		"id_pbill": "pbill",
		"id_untill_users": "untill_users",
		"id_prices": "prices",
		"id_menu": "menus",
		"id_discount_reasons": "discount_reasons",
		"id_smartcards": "smartcards",
		"id_article_options": "article_options",
		"id_size_modifier_item": "size_modifier_item"
	},
	"accounts": {
		"id_payments_sa": "payments"
	},
	"recipe_item": {
		"id_recipe": "recipe",
		"id_inventory_item": "inventory_item",
		"id_unity_used": "unity_conversion",
		"id_recipe_from": "recipe"
	},
	"inv_cm_history": {
		"id_inventory_item": "inventory_item"
	},
	"pbill_cleancash_info": {
		"id_pbill": "pbill"
	},
	"open_discounts": {
		"id_pbill": "pbill"
	},
	"bill_split_rest": {
		"id_pbill": "pbill"
	},
	"option_article_prices": {
		"id_currency": "currency",
		"id_option_article": "option_article",
		"id_prices": "prices"
	},
	"user_messages": {
		"id_untill_users": "untill_users",
		"id_untill_users_from": "untill_users"
	},
	"packing": {},
	"bookkeeping": {},
	"bonus_groups_articles_prices": {
		"id_bonus_groups_articles": "bonus_groups_articles",
		"id_currency": "currency",
		"id_prices": "prices"
	},
	"sold_articles_wm": {
		"id_order_item": "order_item",
		"id_pbill": "pbill"
	},
	"article_ks_notify": {
		"id_articles": "articles",
		"id_ks": "kitchen_screens"
	},
	"countries": {},
	"pbill_zapper_payments_info": {
		"id_zapper_proformas": "zapper_proformas",
		"id_pbill_payments": "pbill_payments"
	},
	"commission": {},
	"table_area": {
		"id_printer_deposit": "printers",
		"id_ksc": "kitchen_screen_counters",
		"id_beco_locations": "beco_locations",
		"id_ticket_deposit": "tickets",
		"id_periods": "periods",
		"id_printers": "printers",
		"id_tickets": "tickets",
		"id_proforma_printer": "printers",
		"id_proforma_ticket": "tickets",
		"id_computers": "computers",
		"id_caller_groups": "caller_groups"
	},
	"article_ingredients": {
		"id_ingredients": "ingredients",
		"id_articles": "articles"
	},
	"article_discount_prices": {
		"id_prices": "prices",
		"id_currency": "currency",
		"id_article_discount": "article_discount"
	},
	"stock_invoice": {
		"id_untill_users": "untill_users",
		"id_purchase_order": "purchase_order",
		"id_stock_locations": "stocking_locations",
		"id_conduct_untill_user": "untill_users",
		"id_suppliers": "suppliers"
	},
	"prepaid_groups": {
		"id_storno_order_article": "articles",
		"id_storno_voucher_article": "articles"
	},
	"allergens": {},
	"inventory": {},
	"client_exceptions": {
		"id_prices": "prices",
		"id_periods": "periods",
		"id_clients": "clients"
	},
	"waste_order_item": {
		"id_order_item": "order_item"
	},
	"transferred_bills": {
		"id_orders_result": "orders",
		"id_orders_original": "orders"
	},
	"vouchers": {
		"id_payments": "payments",
		"id_department": "department",
		"id_untill_users": "untill_users"
	},
	"coupon_payments": {
		"id_coupon_items": "coupon_items",
		"id_order_item": "order_item",
		"id_option_parent": "order_item"
	},
	"restaurant_vars": {
		"id_t2o_autom_user": "untill_users",
		"id_ticket_count_sheet_report": "tickets",
		"id_ticket_count_sheet": "tickets",
		"id_inoutcash_acc": "bookkeeping",
		"id_obs_account": "bookkeeping",
		"id_cashout_payment": "payments",
		"id_ticket_init_count": "tickets",
		"id_tickets_courses": "tickets",
		"id_ticket_order": "tickets",
		"id_ticket_invoice": "tickets",
		"id_savepoint_reason": "discount_reasons",
		"id_stock_locations": "stocking_locations",
		"id_discount_payment": "payments",
		"id_tickets": "tickets"
	},
	"article_bonus_groups": {
		"id_articles": "articles",
		"id_bonus_groups": "bonus_groups"
	},
	"callers": {
		"id_caller_groups": "caller_groups"
	},
	"sales_range": {
		"id_sales_area": "sales_area"
	},
	"license": {},
	"waiter_closetable_area": {
		"id_table_area": "table_area",
		"id_waiters": "waiters"
	},
	"age_groups": {},
	"table_area_computers": {
		"id_table_area": "table_area",
		"id_computer": "computers"
	},
	"order_screens": {
		"id_screen_groups": "screen_groups"
	},
	"waiter_calculation": {
		"id_waiters": "waiters",
		"id_commission": "commission"
	},
	"vd_lcu_dispensers": {
		"id_beco_locations": "beco_locations"
	},
	"stock_physical_count_item": {
		"id_stock_physical_count": "stock_physical_count",
		"id_inventory_item_locations": "inventory_item_locations"
	},
	"discount_group_articles": {
		"id_discount_groups": "discount_groups",
		"id_articles": "articles"
	},
	"currency": {},
	"client_discount_groups_items": {
		"id_client_discount_groups": "client_discount_groups",
		"id_articles": "articles"
	},
	"extra_field_defs": {
		"id_extra_fields": "extra_fields"
	},
	"ks_wf_template": {},
	"bookkeeping_periods": {},
	"restaurant_ordermans": {
		"id_printers_bill": "printers",
		"id_tickets_bill": "tickets",
		"id_printers_proforma": "printers",
		"id_tickets_proforma": "tickets",
		"id_ordermans": "ordermans"
	},
	"article_barcodes": {
		"id_articles": "articles"
	},
	"kitchen_screens": {
		"id_ks_ticket": "tickets",
		"id_ks_printer": "printers"
	},
	"ks_wf_stage_template_item": {
		"id_stage_template": "ks_wf_stage_template",
		"id_kitchen_screens": "kitchen_screens"
	},
	"rent_period_items": {
		"id_rent_periods": "rent_periods"
	},
	"falcon_terminals": {
		"id_computers": "computers",
		"id_screen_groups": "screen_groups"
	},
	"articles_free_options_sm": {
		"id_articles": "articles",
		"id_option_article": "option_article",
		"id_size_modifier_item": "size_modifier_item",
		"id_umc": "unity_conversion",
		"id_recipe": "recipe"
	},
	"clock_in_out": {
		"id_untill_users": "untill_users",
		"id_untill_user_wages": "untill_user_wages"
	},
	"psp_tips": {
		"id_pbill_payments": "pbill_payments",
		"id_pbill": "pbill"
	},
	"cancel_order_item": {
		"id_untill_users": "untill_users",
		"id_prices": "prices",
		"id_sales_area": "sales_area",
		"id_bill": "bill",
		"id_size_modifier_item": "size_modifier_item",
		"id_articles": "articles"
	},
	"daily_balance": {
		"id_articles": "articles"
	},
	"voucher_pbill_payments": {
		"id_vouchers": "vouchers",
		"id_payments": "payments",
		"id_pbill_payments": "pbill_payments",
		"id_voucher_pbill": "voucher_pbill"
	},
	"ingredient_quantity": {
		"id_currency": "currency",
		"id_ingredient_suppliers": "ingredient_suppliers"
	},
	"special_words": {},
	"accounts_payment_items": {
		"id_menu": "account_menus",
		"id_account_payments": "accounts_payments",
		"id_articles": "articles",
		"id_size_modifier_item": "size_modifier_item"
	},
	"exports": {
		"id_export_targets": "export_targets"
	},
	"skins": {},
	"option_article_sm_prices": {
		"id_option_article_prices": "option_article_prices",
		"id_size_modifier_item": "size_modifier_item"
	},
	"waiters": {
		"id_untill_users": "untill_users"
	},
	"article_sm_barcodes": {
		"id_article_barcodes": "article_barcodes",
		"id_size_modifier_item": "size_modifier_item"
	},
	"sales_area": {
		"id_prices": "prices",
		"id_prices_original": "prices",
		"id_scplan": "bo_service_charge"
	},
	"stocking_locations": {
		"id_ticket": "tickets",
		"id_printer": "printers"
	},
	"payment_items": {
		"id_pbill_payments": "pbill_payments",
		"id_pbill": "pbill"
	},
	"articles_ks_wf_item": {
		"id_articles": "articles",
		"id_ks_wf_template_item": "ks_wf_template_item"
	},
	"custom_translations": {},
	"db_tasks": {},
	"packing_kind": {
		"id_packing": "packing"
	},
	"clients": {
		"id_prices_promo": "prices",
		"id_accounts": "accounts",
		"id_extra_field_values": "extra_field_values",
		"id_countries": "countries",
		"id_prices_price": "prices"
	},
	"kitchen_screen_purposes": {},
	"positions": {},
	"bo_service_charge": {},
	"pbill_card_payments_info": {
		"id_pbill_payments": "pbill_payments"
	},
	"discounted_items": {
		"id_order_item": "order_item",
		"id_untill_users": "untill_users",
		"discount_reason": "discount_reasons",
		"id_menu_item": "menu_item",
		"id_discount_groups": "discount_groups"
	},
	"time_articles": {
		"id_order_item": "order_item"
	},
	"ks_wf_template_item": {
		"id_stage_template": "ks_wf_stage_template",
		"id_ks_wf_template": "ks_wf_template"
	},
	"coupon_items": {
		"id_coupons": "coupons"
	},
	"preparation_area": {
		"id_tickets": "tickets",
		"id_stock_locations": "stocking_locations",
		"id_ksc": "kitchen_screen_counters",
		"id_printers": "printers"
	},
	"custom_data": {},
	"sold_articles": {
		"id_pbill": "pbill",
		"id_order_item": "order_item"
	},
	"open_discount_item": {
		"id_order_item": "order_item"
	},
	"article_price_periods": {
		"id_periods": "periods",
		"id_article_prices": "article_prices"
	},
	"user_report_groups": {
		"id_untill_users": "untill_users",
		"id_report_groups": "report_groups"
	},
	"articles_free_options": {
		"id_options": "options",
		"id_articles": "articles"
	},
	"article_size_modifier": {
		"id_inventory_item": "inventory_item",
		"id_recipe": "recipe",
		"id_size_modifier_item": "size_modifier_item",
		"id_articles": "articles",
		"id_unity_sales": "unity_conversion"
	},
	"inventory_item_subst": {
		"id_inventory_item": "inventory_item",
		"id_inventory_item_subst": "inventory_item"
	},
	"option_article_spec_price": {
		"id_option_article_prices": "option_article_prices",
		"id_special_words": "special_words"
	},
	"size_modifier_item": {
		"id_size_modifier": "size_modifier"
	},
	"ks_wf_stage_template": {},
	"waiter_positions": {},
	"menu_screens": {
		"id_screen_groups": "screen_groups"
	},
	"suppliers": {
		"id_countries": "countries",
		"id_currency": "currency"
	},
	"extra_field_values": {},
	"cash_declaration": {
		"id_untill_users": "untill_users"
	},
	"client_discount_groups": {
		"id_clients": "clients",
		"id_accounts": "accounts",
		"id_discount_groups": "discount_groups"
	},
	"article_position_ex": {
		"id_articles": "articles",
		"id_sales_area": "sales_area",
		"id_department": "department"
	},
	"printers": {
		"id_printer_drivers": "printer_drivers",
		"id_ordermans": "ordermans",
		"id_falcon_terminals": "falcon_terminals",
		"id_computers": "computers"
	},
	"recipe": {
		"id_unity_produced": "unity",
		"id_food_group": "food_group"
	},
	"order_item_extra": {
		"id_order_item": "order_item",
		"id_menu_item": "menu_item",
		"id_pbill_item": "pbill_item",
		"id_article_barcodes": "article_barcodes"
	},
	"department": {
		"id_options_condiment": "options",
		"id_age_groups": "age_groups",
		"id_food_group": "food_group",
		"id_options_supplement": "options"
	},
	"payments_hash": {
		"id_payments": "pbill_payments",
		"id_untill_users": "untill_users"
	},
	"stock_open_day_item": {
		"id_inventory_item": "inventory_item",
		"id_stocking_locations": "stocking_locations",
		"id_stock_open_day": "stock_open_day"
	},
	"prepaid_groups_articles": {
		"id_articles": "articles",
		"id_prepaid_groups": "prepaid_groups"
	},
	"inventory_par": {
		"id_periods": "periods",
		"id_inventory_item": "inventory_item"
	},
	"untill_user_fingerprints": {
		"id_untill_users": "untill_users"
	},
	"pbill_payments": {
		"id_driver_discount": "driver_discount",
		"id_pbill": "pbill",
		"id_payments": "payments"
	},
	"order_item_stock_price": {
		"id_order_item": "order_item"
	},
	"computers": {
		"id_screen_groups": "screen_groups",
		"id_tickets_clock": "tickets",
		"id_cash_tickets": "tickets"
	},
	"stock_cost_correction": {
		"id_untill_users": "untill_users",
		"id_stock_locations": "stocking_locations",
		"id_conduct_untill_user": "untill_users",
		"id_inventory_item": "inventory_item"
	},
	"pua_groups": {},
	"untill_group_users": {},
	"cal_orders": {
		"id_callers": "callers",
		"id_users_open": "untill_users",
		"id_users_close": "untill_users",
		"id_orders": "orders"
	},
	"discount_reasons": {
		"id_bookkp": "bookkeeping"
	},
	"table_range": {
		"id_table_area": "table_area"
	},
	"dep_button_setting": {
		"id_department": "department",
		"id_screen_groups": "screen_groups"
	},
	"customer_emails": {
		"id_clients": "clients"
	},
	"order_item_bookp": {
		"id_order_item": "order_item",
		"id_bookkeeping_turnover": "bookkeeping",
		"id_bookkeeping_vat": "bookkeeping"
	},
	"func_panel_tabs": {
		"id_payments": "payments"
	},
	"restaurant_falcons": {
		"id_preparation_area": "preparation_area",
		"id_ks": "kitchen_screens",
		"id_ksc": "kitchen_screen_counters",
		"id_falcon_terminals": "falcon_terminals",
		"id_printers_bill": "printers",
		"id_tickets_bill": "tickets"
	},
	"pbill_hash": {
		"id_pbill_item": "pbill_item",
		"id_untill_users": "untill_users"
	},
	"stock_open_day": {},
	"bonus_groups_articles": {
		"id_bonus_groups": "bonus_groups",
		"id_articles": "articles"
	},
	"kitchen_screens_link": {
		"id_ks_to": "kitchen_screens",
		"id_ks_from": "kitchen_screens"
	},
	"article_notify": {
		"id_preparation_area": "preparation_area",
		"id_articles": "articles"
	},
	"stock_adjustment_item": {
		"id_inventory_item": "inventory_item",
		"id_stock_adjustment": "stock_adjustment"
	},
	"articles_periods": {
		"id_articles": "articles",
		"id_periods": "periods"
	},
	"olap_db_sers": {},
	"rent_periods_articles": {
		"id_articles": "articles",
		"id_rent_period_items": "rent_period_items"
	},
	"neg_orders": {
		"id_orders": "orders",
		"id_discount_reasons": "discount_reasons",
		"id_manager": "untill_users"
	},
	"export_targets": {},
	"option_tree": {
		"id_options_parent": "options",
		"id_options_child": "options"
	},
	"screen_images": {},
	"future_bills": {
		"id_untill_users": "untill_users",
		"id_clients": "clients"
	},
	"articles": {
		"id_size_modifier": "size_modifier",
		"id_packing": "packing",
		"id_recipe": "recipe",
		"id_beco_group": "beco_groups",
		"id_pua_groups": "pua_groups",
		"id_age_groups": "age_groups",
		"id_ksc": "kitchen_screen_counters",
		"id_currency": "currency",
		"id_promotions": "promotions",
		"id_food_group": "food_group",
		"id_free_option": "options",
		"id_suppliers": "suppliers",
		"id_ks_wf": "ks_wf_template",
		"id_rent_periods": "rent_periods",
		"id_beco_location": "beco_locations",
		"id_rental_group": "rental_group",
		"id_departament": "department",
		"id_courses": "courses",
		"id_commission": "commission",
		"id_vd_group": "vd_groups",
		"id_inventory_item": "inventory_item",
		"id_unity_sales": "unity_conversion",
		"id_article_ksp": "kitchen_screen_purposes",
		"id_extra_field_values": "extra_field_values"
	},
	"article_options": {
		"id_options": "options",
		"id_articles": "articles",
		"id_courses": "courses"
	},
	"eft_config_selections": {
		"id_payments": "payments"
	},
	"tickets": {},
	"order_item_onhold": {
		"id_order_item": "order_item"
	},
	"size_modifier": {},
	"computer_devices": {
		"id_computers": "computers"
	},
	"options": {},
	"discount_groups": {
		"id_discount_reasons": "discount_reasons"
	},
	"periodical_reports": {
		"id_tickets": "tickets"
	},
	"printers_mapping": {
		"id_from_printer": "printers",
		"id_to_printer": "printers"
	},
	"computer_drawers": {
		"id_drawers": "printers",
		"id_computers": "computers"
	},
	"pbill_hotel_payments_info": {
		"id_pbill_payments": "pbill_payments"
	},
	"settings": {
		"id_bookkp_vat": "bookkeeping",
		"id_bookkp_paymentk": "bookkeeping",
		"id_bookkp_costcor": "bookkeeping",
		"id_bookkp_physvar": "bookkeeping",
		"id_bookkp_turnover": "bookkeeping",
		"id_bookkp_target": "export_targets",
		"id_bookkp_cos": "bookkeeping",
		"id_bookkp_stockrcvd": "bookkeeping",
		"id_bookkp_writeoff": "bookkeeping",
		"id_bookkp_inventory": "bookkeeping",
		"id_holiday": "periods",
		"id_bookkp_payment": "bookkeeping",
		"id_msglayout": "tickets",
		"id_bookkp_turnoverk": "bookkeeping",
		"id_bookkp_vatk": "bookkeeping"
	},
	"pbill_return": {
		"id_void_reason": "discount_reasons",
		"id_pbill": "pbill"
	},
	"supplier_item": {
		"id_inventory_item": "inventory_item",
		"id_unity_purchase": "unity_conversion",
		"id_suppliers": "suppliers"
	},
	"voided_items": {
		"id_order_item": "order_item",
		"id_void_reason": "discount_reasons",
		"id_untill_users": "untill_users"
	},
	"order_item_newyse_data": {
		"id_order_item": "order_item",
		"id_prepaid_groups": "prepaid_groups"
	},
	"kitchen_screen_counters": {
		"id_pu_printers": "printers",
		"id_pu_tickets": "tickets"
	},
	"pbill_email": {
		"id_pbill": "pbill"
	},
	"option_sales_area": {
		"id_options": "options",
		"id_sales_area": "sales_area"
	},
	"pbill_item_bookp": {
		"id_pbill_item": "pbill_item",
		"id_bookkeeping_turnover": "bookkeeping",
		"id_bookkeeping_vat": "bookkeeping"
	},
	"inventory_categories": {
		"id_count_frequency": "count_frequencies"
	},
	"stock_invoice_item": {
		"id_inventory_item": "inventory_item",
		"id_supplier_item": "supplier_item",
		"id_stock_invoice": "stock_invoice"
	},
	"vd_aliases": {},
	"rent_units": {
		"id_articles": "articles"
	},
	"pa_ks_notify": {
		"id_preparation_area": "preparation_area",
		"id_ks": "kitchen_screens"
	},
	"food_group": {
		"id_bookkp_turnover": "bookkeeping",
		"id_bookkp_vat": "bookkeeping",
		"id_category": "category",
		"id_bookkp_vat_sec": "bookkeeping"
	},
	"rental_group": {},
	"beco_article_locations": {
		"id_articles": "articles",
		"id_locations": "beco_locations"
	},
	"rent_repair_reasons": {},
	"cash_declaration_items": {
		"id_cash_declaration": "cash_declaration",
		"id_currency_notes_coins": "currency_notes_coins"
	},
	"olap_db": {},
	"voucher_payments": {
		"id_vouchers": "vouchers",
		"id_pbill_payments": "pbill_payments"
	},
	"article_sm_price_periods": {
		"id_article_price_periods": "article_price_periods",
		"id_size_modifier_item": "size_modifier_item"
	},
	"global_scripts": {},
	"courses": {
		"id_ks_ticket": "tickets",
		"id_ks_printer": "printers",
		"id_pu_printer": "printers",
		"id_pu_ticket": "tickets"
	},
	"article_discount": {
		"id_articles": "articles",
		"id_currency": "currency"
	},
	"order_item_newyse_prices": {
		"id_order_item": "order_item"
	},
	"ordermans": {
		"id_menu": "menu_screens",
		"id_screen_groups": "screen_groups",
		"id_computers": "computers",
		"id_start_screen": "order_screens"
	},
	"bonus_groups": {},
	"rent_periods": {},
	"department_available": {
		"id_sales_area": "sales_area",
		"id_department": "department"
	},
	"func_panel_settings": {},
	"article_size_modifier_price": {
		"id_article_prices": "article_prices",
		"id_size_modifier_item": "size_modifier_item"
	},
	"tpapi_tokens": {},
	"purchase_order_item": {
		"id_purchase_order": "purchase_order",
		"id_inventory_item": "inventory_item",
		"id_supplier_item": "supplier_item"
	},
	"bill_reprints": {
		"id_pbill": "pbill",
		"id_untill_users": "untill_users"
	},
	"orders_newyse_data": {
		"id_orders": "orders"
	},
	"discounts": {
		"id_category": "category",
		"id_discount_reasons": "discount_reasons",
		"id_periods": "periods",
		"id_department": "department",
		"id_courses": "courses",
		"id_food_group": "food_group"
	},
	"article_prices": {
		"id_prices": "prices",
		"id_currency": "currency",
		"id_articles": "articles"
	},
	"notes_coins": {},
	"ug_report_groups": {
		"id_ug": "untill_group_users",
		"id_report_groups": "report_groups"
	},
	"printer_drivers": {},
	"default_entities": {},
	"purchase_order": {
		"id_conduct_untill_user": "untill_users",
		"id_suppliers": "suppliers",
		"id_untill_users": "untill_users"
	},
	"deposit_card_payments_info": {
		"id_deposits": "account_deposits",
		"id_vouchers": "vouchers"
	},
	"wm_tasks": {},
	"order_item_sizes": {
		"id_order_item": "order_item",
		"id_menu_item": "menu_item",
		"id_pbill_item": "pbill_item",
		"id_articles": "articles",
		"id_size_modifier_item": "size_modifier_item"
	},
	"period_values": {
		"id_periods": "periods"
	},
	"article_available": {
		"id_sales_area": "sales_area",
		"id_periods": "periods",
		"id_articles": "articles"
	},
	"pbill_item_refund": {
		"id_untill_users": "untill_users",
		"id_courses": "courses",
		"id_menu": "menus",
		"id_pbill": "pbill",
		"id_articles": "articles",
		"id_department": "department",
		"id_food_group": "food_group",
		"id_category": "category",
		"id_prices": "prices"
	},
	"extra_fields": {},
	"bonus_items": {
		"id_article_bonus_groups": "bonus_groups",
		"id_parent_menu_item": "menu_item",
		"id_parent_bonus_article": "articles",
		"id_order_item": "order_item",
		"id_parent_item": "order_item"
	},
	"article_button_setting": {
		"id_articles": "articles",
		"id_screen_groups": "screen_groups"
	},
	"payment_bookkeeping": {
		"id_payments": "payments",
		"id_bookkeeping": "bookkeeping"
	},
	"ticket_logos": {},
	"stock_cost_correction_item": {
		"id_stock_cost_correction": "stock_cost_correction",
		"id_stock_invoice_item": "stock_invoice_item"
	},
	"zip_codes": {},
	"sync_db_sers": {},
	"bars": {},
	"inventory_item_locations": {
		"id_inventory_item": "inventory_item",
		"id_stocking_locations": "stocking_locations",
		"id_unity_counting": "unity_conversion"
	},
	"bo_sc_items": {
		"id_department": "department",
		"id_food_group": "food_group",
		"id_bsc": "bo_service_charge",
		"id_category": "category"
	},
	"pbill_balance": {
		"id_pbill": "pbill",
		"id_clients": "clients",
		"id_accounts": "accounts"
	},
	"user_updates": {
		"id_untill_users": "untill_users",
		"id_update_user": "untill_users"
	},
	"suppliers_contacts": {
		"id_suppliers": "suppliers"
	},
	"t2o_members": {
		"id_t2o_groups": "t2o_groups",
		"id_clients": "clients",
		"id_users_join": "untill_users",
		"id_users_quit": "untill_users"
	},
	"account_payment_data": {
		"id_pbill_payments": "pbill_payments"
	},
	"eft_config_sel_avail": {
		"id_falcon_terminals": "falcon_terminals",
		"id_ordermans": "ordermans",
		"id_eft_config_selections": "eft_config_selections",
		"id_computers": "computers"
	},
	"complete_meal": {
		"id_pbill": "pbill",
		"id_untill_users": "untill_users"
	},
	"pbill_payer": {
		"id_pbill_payments": "pbill_payments"
	},
	"extra_field_items": {
		"id_extra_field_values": "extra_field_values",
		"id_extra_field_defs": "extra_field_defs"
	},
	"smartcards_turnover": {
		"id_untill_users": "untill_users",
		"id_smartcards": "smartcards",
		"id_pbill_payments": "pbill_payments",
		"id_payments": "payments",
		"id_deposit_bookkeeping": "bookkeeping"
	},
	"func_panel_tab_buttons": {
		"id_func_panel_tabs": "func_panel_tabs",
		"id_payments": "payments"
	},
	"articles_allergens": {
		"id_allergens": "allergens",
		"id_articles": "articles"
	},
	"order_item": {
		"id_article_options": "article_options",
		"id_size_modifier_item": "size_modifier_item",
		"id_orders": "orders",
		"id_articles": "articles",
		"id_prices": "prices",
		"id_menu": "menus",
		"id_courses": "courses",
		"id_option_article": "option_article",
		"id_smartcards": "smartcards"
	},
	"componoud_device_drivers": {
		"id_computer_devices": "computer_devices"
	},
	"inv_loc_period_normal": {
		"id_periods": "periods",
		"id_inventory_item_locations": "inventory_item_locations"
	},
	"smartcardordergroups": {
		"id_smartcards": "smartcard_groups"
	},
	"bg_sm_prices": {
		"id_bg_articles_prices": "bonus_groups_articles_prices",
		"id_size_modifier_item": "size_modifier_item"
	},
	"smartcards": {
		"id_smartcard_groups": "smartcard_groups",
		"id_clients": "clients"
	},
	"ingredient_suppliers": {
		"id_suppliers": "suppliers",
		"id_ingredients": "ingredients"
	},
	"waiter_table_area": {
		"id_table_area": "table_area",
		"id_waiters": "waiters"
	},
	"unity_conversion": {
		"id_unity": "unity",
		"id_unity_convert": "unity"
	},
	"pua_groups_sales_area": {
		"id_pua_groups": "pua_groups",
		"id_sales_area": "sales_area"
	},
	"report_groups": {},
	"payments": {
		"id_bookkp": "bookkeeping",
		"id_currency": "currency"
	},
	"stock_units": {},
	"moved_tables": {
		"id_untill_users": "untill_users",
		"id_screen_group": "screen_groups"
	},
	"order_item_allergens": {
		"id_order_item": "order_item",
		"id_menu_item": "menu_item",
		"id_allergens": "allergens",
		"id_pbill_item": "pbill_item"
	},
	"table_printer": {
		"id_stock_locations": "stocking_locations",
		"id_ksc": "kitchen_screen_counters",
		"id_printers": "printers",
		"id_tickets": "tickets",
		"id_table_area": "table_area",
		"id_preparation_area": "preparation_area"
	},
	"unity": {},
	"sync_db_sers_p": {},
	"vd_receipts": {
		"id_article": "articles",
		"id_receipt_article": "articles"
	},
	"func_payment_buttons": {},
	"prices": {},
	"promotions": {},
	"ingredients": {
		"id_unity_purchase": "unity",
		"id_unity_sales": "unity",
		"id_currency": "currency"
	},
	"restaurant_computers": {
		"id_psp_layout": "tickets",
		"id_rear_disp_printer": "printers",
		"id_init_ksc": "kitchen_screen_counters",
		"id_tickets_fiscal_footer": "tickets",
		"id_ta_total_layout": "tickets",
		"id_printers_proforma": "printers",
		"id_rear_disp_article_layout": "tickets",
		"id_beco_location": "beco_locations",
		"id_tickets_order_journal": "tickets",
		"id_ticket_voucher_bunch": "tickets",
		"id_tickets_bill": "tickets",
		"id_tickets_journal": "tickets",
		"id_tickets_taorder": "tickets",
		"id_second_article_layout": "tickets",
		"id_printers_void": "printers",
		"id_tickets_proforma": "tickets",
		"id_tickets_control_journal": "tickets",
		"id_printers_taorder": "printers",
		"id_rear_disp_bill_layout": "tickets",
		"id_oif_preparation_area": "preparation_area",
		"id_tickets_void": "tickets",
		"id_screens_order": "screens",
		"id_printers_giftcards": "printers",
		"id_journal_printer": "printers",
		"id_return_layout": "tickets",
		"id_tickets_voucher": "tickets",
		"id_email_invoice_layout": "tickets",
		"id_ticket_voucher_bill": "tickets",
		"id_sales_area": "sales_area",
		"id_rent_printer": "printers",
		"id_reprint_order": "tickets",
		"id_screens_part": "screens",
		"id_inout_layout": "tickets",
		"id_inout_printer": "printers",
		"id_coupon_layout": "tickets",
		"id_screens_payment": "screens",
		"id_rear_screen_saver": "tickets",
		"id_tickets_giftcards": "tickets",
		"id_tickets_manager": "tickets",
		"id_stock_location": "stocking_locations",
		"id_drawer_layout": "tickets",
		"id_printers_voucher": "printers",
		"id_screens_condiment": "screens",
		"id_deposit_layout": "tickets",
		"id_deposit_printer": "printers",
		"id_printers_1": "printers",
		"id_periods": "periods",
		"id_invoice_layout": "tickets",
		"id_computers": "computers",
		"id_init_ks": "kitchen_screens",
		"id_stock_printer": "printers",
		"id_tickets_preauth": "tickets",
		"id_screens_supplement": "screens",
		"id_rent_layout": "tickets",
		"id_printers_manager": "printers",
		"id_tickets_reopen": "tickets",
		"id_printers_reopen": "printers",
		"id_tickets_prof_fiscal_footer": "tickets"
	},
	"pbill": {
		"id_real_untill_user": "untill_users",
		"id_untill_users": "untill_users",
		"id_sales_area": "sales_area",
		"id_clients": "clients",
		"id_currency": "currency"
	},
	"account_deposits": {
		"id_untill_users": "untill_users",
		"id_clients": "clients",
		"id_payments": "payments",
		"id_sales_area": "sales_area",
		"id_bookkeeping": "bookkeeping"
	},
	"abg_sm_prices": {
		"id_article_bonus_prices": "article_bonus_prices",
		"id_size_modifier_item": "size_modifier_item"
	},
	"category": {},
	"sales_area_exceptions": {
		"id_periods": "periods",
		"id_prices": "prices",
		"id_sales_area": "sales_area"
	},
	"t2o_groups": {
		"id_clients": "clients",
		"id_users_created": "untill_users",
		"id_users_closed": "untill_users"
	},
	"beco_locations": {},
	"computer_users": {
		"id_computers": "computers",
		"id_untill_users": "untill_users"
	},
	"table_area_ks": {
		"id_table_area": "table_area",
		"id_ks_from": "kitchen_screens",
		"id_ks_to": "kitchen_screens",
		"id_periods": "periods"
	},
	"system_vars": {},
	"cancelled_task_recipients": {
		"id_db_tasks_recipients": "db_tasks_recipients"
	},
	"order_type": {},
	"bill": {
		"id_user_proforma": "untill_users",
		"id_cardprice": "prices",
		"id_discount_reasons": "discount_reasons",
		"id_untill_users": "untill_users",
		"id_clients": "clients",
		"id_courses": "courses",
		"id_t2o_groups": "t2o_groups",
		"id_order_type": "order_type",
		"id_alter_user": "untill_users",
		"id_time_article": "articles",
		"id_bo_service_charge": "bo_service_charge",
		"id_serving_time": "serving_time",
		"id_callers_last": "callers"
	},
	"smartcard_tables": {
		"id_smartcards": "smartcards"
	},
	"client_smartcard_uids": {
		"id_clients": "clients"
	},
	"kitchen_screens_substations": {
		"id_ks_sub": "kitchen_screens",
		"id_ks_main": "kitchen_screens"
	},
	"menu_item": {
		"id_options": "options",
		"id_option_article": "option_article",
		"id_size_modifier_item": "size_modifier_item",
		"id_article_options": "article_options",
		"id_articles": "articles",
		"id_prices": "prices",
		"id_courses": "courses",
		"id_menu": "menus"
	},
	"menu_item_newyse_data": {
		"id_menu_item": "menu_item",
		"id_prepaid_groups": "prepaid_groups"
	},
	"menu_item_bookp": {
		"id_bookkeeping_turnover": "bookkeeping",
		"id_bookkeeping_vat": "bookkeeping",
		"id_menu_item": "menu_item"
	},
	"menu_item_newyse_prices": {
		"id_menu_item": "menu_item"
	},
	"menus": {},
	"smartcard_table_cards": {
		"id_smartcards": "smartcards",
		"id_smartcard_tables": "smartcard_tables"
	},
	"apostill_hddcodes": {
		"id_dealers": "dealers"
	},
	"client_cards": {
		"id_clients": "clients",
		"id_client_cards_name": "client_card_names"
	},
	"dealers": {
		"id_clients": "clients",
		"id_banks": "banks"
	},
	"pbill_cashm_payments_info": {
		"id_pbill_payments": "pbill_payments"
	},
	"client_card_names": {},
	"banks": {
		"id_currency": "currency",
		"id_order_layout": "tickets"
	},
	"licenses": {
		"id_dealers": "dealers",
		"id_licenses_prev": "licenses",
		"id_bill": "bill"
	},
	"serving_time": {},
	"art_free_opt_defaults": {
		"id_articles_free_options": "articles_free_options",
		"id_option_article": "option_article"
	},
	"dep_position_ex": {
		"id_sales_area": "sales_area",
		"id_department": "department"
	},
	"licenses_online": {
		"id_licenses": "licenses"
	},
	"kitchen_screen_alert_periods": {
		"id_kitchen_screens": "kitchen_screens",
		"id_periods": "periods"
	},
	"air_table_plan": {},
	"air_table_plan_item": {
		"id_air_table_plan": "air_table_plan"
	},
	"air_article_messages": {}
};

export default ForeignKeys;