/*
 * Copyright (c) 2021-present unTill Pro, Ltd.
 */

// auto generated by airs-importbo. DO NOT EDIT.

const ForeignKeys = {
	"untill.currency_notes_coins": {
		"id_currency": "untill.currency",
		"id_notes_coins": "untill.notes_coins"
	},
	"untill.pos_emails": {},
	"untill.orders": {
		"id_untill_users": "untill.untill_users",
		"id_sales_area": "untill.sales_area",
		"id_table_area": "untill.table_area"
	},
	"untill.oi_onhold_logoff": {
		"id_order_item": "untill.order_item"
	},
	"untill.eft_config_sel_items": {
		"id_eft_config_selections": "untill.eft_config_selections"
	},
	"untill.order_coupon_items": {
		"id_order_item": "untill.order_item",
		"id_coupon_item": "untill.coupon_items"
	},
	"untill.pbill_payments_bookp": {
		"id_pbill_payments": "untill.pbill_payments",
		"id_bookkeeping": "untill.bookkeeping"
	},
	"untill.accounts_payments": {
		"id_untill_users": "untill.untill_users",
		"id_clients": "untill.clients",
		"id_sales_area": "untill.sales_area",
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.department_articles": {
		"id_articles": "untill.articles",
		"id_department": "untill.department"
	},
	"untill.vd_groups": {},
	"untill.inventory_item": {
		"id_unity": "untill.unity",
		"id_inventory_categories": "untill.inventory_categories",
		"id_count_frequencies": "untill.count_frequencies",
		"id_recipe": "untill.recipe"
	},
	"untill.beco_groups": {},
	"untill.stock_doc": {
		"id_orders": "untill.orders",
		"id_pbill": "untill.pbill",
		"id_stock_invoice": "untill.stock_invoice",
		"id_stock_adjustment": "untill.stock_adjustment",
		"id_stock_cost_correction": "untill.stock_cost_correction"
	},
	"untill.keys": {},
	"untill.falcon_screens": {
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.smartcard_groups": {
		"id_prices": "untill.prices",
		"id_payments": "untill.payments"
	},
	"untill.untill_user_wages": {
		"id_untill_users": "untill.untill_users",
		"id_waiter_positions": "untill.waiter_positions"
	},
	"untill.coupon_templates": {
		"id_options": "untill.options",
		"id_prices": "untill.prices"
	},
	"untill.stock_adjustment": {
		"id_untill_users": "untill.untill_users",
		"id_transfer_to": "untill.stock_units",
		"id_stock_locations": "untill.stocking_locations",
		"id_stock_locations_to": "untill.stocking_locations",
		"id_conduct_untill_user": "untill.untill_users",
		"id_spc": "untill.stock_physical_count"
	},
	"untill.screens": {
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.coupons": {
		"id_untill_users": "untill.untill_users",
		"id_coupon_templates": "untill.coupon_templates",
		"id_articles": "untill.articles"
	},
	"untill.bo_bookmarks": {},
	"untill.ta_ks_notify": {
		"id_ks": "untill.kitchen_screens",
		"id_table_printer": "untill.table_printer"
	},
	"untill.periods": {},
	"untill.neg_pbill": {
		"id_pbill": "untill.pbill",
		"id_pbill_close": "untill.pbill"
	},
	"untill.untill_users": {
		"id_countries": "untill.countries",
		"id_group_users": "untill.untill_group_users"
	},
	"untill.article_options_defaults": {
		"id_article_options": "untill.article_options",
		"id_option_article": "untill.option_article"
	},
	"untill.db_tasks_recipients": {
		"id_db_tasks": "untill.db_tasks"
	},
	"untill.pua_groups_articles": {
		"id_pua_groups": "untill.pua_groups",
		"id_articles": "untill.articles"
	},
	"untill.report_group_tickets": {
		"id_tickets": "untill.tickets",
		"id_report_groups": "untill.report_groups"
	},
	"untill.break_reasons": {},
	"untill.article_garbagecol": {
		"id_articles": "untill.articles"
	},
	"untill.blacklist": {
		"id_clients": "untill.clients"
	},
	"untill.count_frequencies": {},
	"untill.stock_physical_count": {
		"id_count_frequencies": "untill.count_frequencies",
		"id_stock_locations": "untill.stocking_locations",
		"id_conduct_untill_user": "untill.untill_users"
	},
	"untill.option_article": {
		"id_articles": "untill.articles",
		"id_options": "untill.options"
	},
	"untill.screen_groups": {},
	"untill.article_bonus_prices": {
		"id_prices": "untill.prices",
		"id_article_bonus_groups": "untill.article_bonus_groups",
		"id_currency": "untill.currency"
	},
	"untill.drawer_payments": {
		"id_payments": "untill.payments",
		"id_drawers": "untill.printers"
	},
	"untill.caller_groups": {},
	"untill.pbill_item": {
		"id_articles": "untill.articles",
		"id_courses": "untill.courses",
		"id_option_article": "untill.option_article",
		"id_pbill": "untill.pbill",
		"id_untill_users": "untill.untill_users",
		"id_prices": "untill.prices",
		"id_menu": "untill.menus",
		"id_discount_reasons": "untill.discount_reasons",
		"id_smartcards": "untill.smartcards",
		"id_article_options": "untill.article_options",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.accounts": {
		"id_payments_sa": "untill.payments"
	},
	"untill.recipe_item": {
		"id_recipe": "untill.recipe",
		"id_inventory_item": "untill.inventory_item",
		"id_unity_used": "untill.unity_conversion",
		"id_recipe_from": "untill.recipe"
	},
	"untill.inv_cm_history": {
		"id_inventory_item": "untill.inventory_item"
	},
	"untill.pbill_cleancash_info": {
		"id_pbill": "untill.pbill"
	},
	"untill.open_discounts": {
		"id_pbill": "untill.pbill"
	},
	"untill.bill_split_rest": {
		"id_pbill": "untill.pbill"
	},
	"untill.option_article_prices": {
		"id_currency": "untill.currency",
		"id_option_article": "untill.option_article",
		"id_prices": "untill.prices"
	},
	"untill.user_messages": {
		"id_untill_users": "untill.untill_users",
		"id_untill_users_from": "untill.untill_users"
	},
	"untill.packing": {},
	"untill.bookkeeping": {},
	"untill.bonus_groups_articles_prices": {
		"id_bonus_groups_articles": "untill.bonus_groups_articles",
		"id_currency": "untill.currency",
		"id_prices": "untill.prices"
	},
	"untill.sold_articles_wm": {
		"id_order_item": "untill.order_item",
		"id_pbill": "untill.pbill"
	},
	"untill.article_ks_notify": {
		"id_articles": "untill.articles",
		"id_ks": "untill.kitchen_screens"
	},
	"untill.countries": {},
	"untill.pbill_zapper_payments_info": {
		"id_zapper_proformas": "zapper_proformas",
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.commission": {},
	"untill.table_area": {
		"id_printer_deposit": "untill.printers",
		"id_ksc": "untill.kitchen_screen_counters",
		"id_beco_locations": "untill.beco_locations",
		"id_ticket_deposit": "untill.tickets",
		"id_periods": "untill.periods",
		"id_printers": "untill.printers",
		"id_tickets": "untill.tickets",
		"id_proforma_printer": "untill.printers",
		"id_proforma_ticket": "untill.tickets",
		"id_computers": "untill.computers",
		"id_caller_groups": "untill.caller_groups"
	},
	"untill.article_ingredients": {
		"id_ingredients": "untill.ingredients",
		"id_articles": "untill.articles"
	},
	"untill.article_discount_prices": {
		"id_prices": "untill.prices",
		"id_currency": "untill.currency",
		"id_article_discount": "untill.article_discount"
	},
	"untill.stock_invoice": {
		"id_untill_users": "untill.untill_users",
		"id_purchase_order": "untill.purchase_order",
		"id_stock_locations": "untill.stocking_locations",
		"id_conduct_untill_user": "untill.untill_users",
		"id_suppliers": "untill.suppliers"
	},
	"untill.prepaid_groups": {
		"id_storno_order_article": "untill.articles",
		"id_storno_voucher_article": "untill.articles"
	},
	"untill.allergens": {},
	"untill.inventory": {},
	"untill.client_exceptions": {
		"id_prices": "untill.prices",
		"id_periods": "untill.periods",
		"id_clients": "untill.clients"
	},
	"untill.waste_order_item": {
		"id_order_item": "untill.order_item"
	},
	"untill.transferred_bills": {
		"id_orders_result": "untill.orders",
		"id_orders_original": "untill.orders"
	},
	"untill.vouchers": {
		"id_payments": "untill.payments",
		"id_department": "untill.department",
		"id_untill_users": "untill.untill_users"
	},
	"untill.coupon_payments": {
		"id_coupon_items": "untill.coupon_items",
		"id_order_item": "untill.order_item",
		"id_option_parent": "untill.order_item"
	},
	"untill.restaurant_vars": {
		"id_t2o_autom_user": "untill.untill_users",
		"id_ticket_count_sheet_report": "untill.tickets",
		"id_ticket_count_sheet": "untill.tickets",
		"id_inoutcash_acc": "untill.bookkeeping",
		"id_obs_account": "untill.bookkeeping",
		"id_cashout_payment": "untill.payments",
		"id_ticket_init_count": "untill.tickets",
		"id_tickets_courses": "untill.tickets",
		"id_ticket_order": "untill.tickets",
		"id_ticket_invoice": "untill.tickets",
		"id_savepoint_reason": "untill.discount_reasons",
		"id_stock_locations": "untill.stocking_locations",
		"id_discount_payment": "untill.payments",
		"id_tickets": "untill.tickets"
	},
	"untill.article_bonus_groups": {
		"id_articles": "untill.articles",
		"id_bonus_groups": "untill.bonus_groups"
	},
	"untill.callers": {
		"id_caller_groups": "untill.caller_groups"
	},
	"untill.sales_range": {
		"id_sales_area": "untill.sales_area"
	},
	"untill.license": {},
	"untill.waiter_closetable_area": {
		"id_table_area": "untill.table_area",
		"id_waiters": "untill.waiters"
	},
	"untill.age_groups": {},
	"untill.table_area_computers": {
		"id_table_area": "untill.table_area",
		"id_computer": "untill.computers"
	},
	"untill.order_screens": {
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.waiter_calculation": {
		"id_waiters": "untill.waiters",
		"id_commission": "untill.commission"
	},
	"untill.vd_lcu_dispensers": {
		"id_beco_locations": "untill.beco_locations"
	},
	"untill.stock_physical_count_item": {
		"id_stock_physical_count": "untill.stock_physical_count",
		"id_inventory_item_locations": "untill.inventory_item_locations"
	},
	"untill.discount_group_articles": {
		"id_discount_groups": "untill.discount_groups",
		"id_articles": "untill.articles"
	},
	"untill.currency": {},
	"untill.client_discount_groups_items": {
		"id_client_discount_groups": "untill.client_discount_groups",
		"id_articles": "untill.articles"
	},
	"untill.extra_field_defs": {
		"id_extra_fields": "untill.extra_fields"
	},
	"untill.ks_wf_template": {},
	"untill.bookkeeping_periods": {},
	"untill.restaurant_ordermans": {
		"id_printers_bill": "untill.printers",
		"id_tickets_bill": "untill.tickets",
		"id_printers_proforma": "untill.printers",
		"id_tickets_proforma": "untill.tickets",
		"id_ordermans": "untill.ordermans"
	},
	"untill.article_barcodes": {
		"id_articles": "untill.articles"
	},
	"untill.kitchen_screens": {
		"id_ks_ticket": "untill.tickets",
		"id_ks_printer": "untill.printers"
	},
	"untill.ks_wf_stage_template_item": {
		"id_stage_template": "untill.ks_wf_stage_template",
		"id_kitchen_screens": "untill.kitchen_screens"
	},
	"untill.rent_period_items": {
		"id_rent_periods": "untill.rent_periods"
	},
	"untill.falcon_terminals": {
		"id_computers": "untill.computers",
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.articles_free_options_sm": {
		"id_articles": "untill.articles",
		"id_option_article": "untill.option_article",
		"id_size_modifier_item": "untill.size_modifier_item",
		"id_umc": "untill.unity_conversion",
		"id_recipe": "untill.recipe"
	},
	"untill.clock_in_out": {
		"id_untill_users": "untill.untill_users",
		"id_untill_user_wages": "untill.untill_user_wages"
	},
	"untill.psp_tips": {
		"id_pbill_payments": "untill.pbill_payments",
		"id_pbill": "untill.pbill"
	},
	"untill.cancel_order_item": {
		"id_untill_users": "untill.untill_users",
		"id_prices": "untill.prices",
		"id_sales_area": "untill.sales_area",
		"id_bill": "untill.bill",
		"id_size_modifier_item": "untill.size_modifier_item",
		"id_articles": "untill.articles"
	},
	"untill.daily_balance": {
		"id_articles": "untill.articles"
	},
	"untill.voucher_pbill_payments": {
		"id_vouchers": "untill.vouchers",
		"id_payments": "untill.payments",
		"id_pbill_payments": "untill.pbill_payments",
		"id_voucher_pbill": "untill.voucher_pbill"
	},
	"untill.ingredient_quantity": {
		"id_currency": "untill.currency",
		"id_ingredient_suppliers": "untill.ingredient_suppliers"
	},
	"untill.special_words": {},
	"untill.accounts_payment_items": {
		"id_menu": "untill.account_menus",
		"id_account_payments": "untill.accounts_payments",
		"id_articles": "untill.articles",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.exports": {
		"id_export_targets": "untill.export_targets"
	},
	"untill.skins": {},
	"untill.option_article_sm_prices": {
		"id_option_article_prices": "untill.option_article_prices",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.waiters": {
		"id_untill_users": "untill.untill_users"
	},
	"untill.article_sm_barcodes": {
		"id_article_barcodes": "untill.article_barcodes",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.sales_area": {
		"id_prices": "untill.prices",
		"id_prices_original": "untill.prices",
		"id_scplan": "untill.bo_service_charge"
	},
	"untill.stocking_locations": {
		"id_ticket": "untill.tickets",
		"id_printer": "untill.printers"
	},
	"untill.payment_items": {
		"id_pbill_payments": "untill.pbill_payments",
		"id_pbill": "untill.pbill"
	},
	"untill.articles_ks_wf_item": {
		"id_articles": "untill.articles",
		"id_ks_wf_template_item": "untill.ks_wf_template_item"
	},
	"untill.custom_translations": {},
	"untill.db_tasks": {},
	"untill.packing_kind": {
		"id_packing": "untill.packing"
	},
	"untill.clients": {
		"id_prices_promo": "untill.prices",
		"id_accounts": "untill.accounts",
		"id_extra_field_values": "untill.extra_field_values",
		"id_countries": "untill.countries",
		"id_prices_price": "untill.prices"
	},
	"untill.kitchen_screen_purposes": {},
	"untill.positions": {},
	"untill.bo_service_charge": {},
	"untill.pbill_card_payments_info": {
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.discounted_items": {
		"id_order_item": "untill.order_item",
		"id_untill_users": "untill.untill_users",
		"discount_reason": "untill.discount_reasons",
		"id_menu_item": "untill.menu_item",
		"id_discount_groups": "untill.discount_groups"
	},
	"untill.time_articles": {
		"id_order_item": "untill.order_item"
	},
	"untill.ks_wf_template_item": {
		"id_stage_template": "untill.ks_wf_stage_template",
		"id_ks_wf_template": "untill.ks_wf_template"
	},
	"untill.coupon_items": {
		"id_coupons": "untill.coupons"
	},
	"untill.preparation_area": {
		"id_tickets": "untill.tickets",
		"id_stock_locations": "untill.stocking_locations",
		"id_ksc": "untill.kitchen_screen_counters",
		"id_printers": "untill.printers"
	},
	"untill.custom_data": {},
	"untill.sold_articles": {
		"id_pbill": "untill.pbill",
		"id_order_item": "untill.order_item"
	},
	"untill.open_discount_item": {
		"id_order_item": "untill.order_item"
	},
	"untill.article_price_periods": {
		"id_periods": "untill.periods",
		"id_article_prices": "untill.article_prices"
	},
	"untill.user_report_groups": {
		"id_untill_users": "untill.untill_users",
		"id_report_groups": "untill.report_groups"
	},
	"untill.articles_free_options": {
		"id_options": "untill.options",
		"id_articles": "untill.articles"
	},
	"untill.article_size_modifier": {
		"id_inventory_item": "untill.inventory_item",
		"id_recipe": "untill.recipe",
		"id_size_modifier_item": "untill.size_modifier_item",
		"id_articles": "untill.articles",
		"id_unity_sales": "untill.unity_conversion"
	},
	"untill.inventory_item_subst": {
		"id_inventory_item": "untill.inventory_item",
		"id_inventory_item_subst": "untill.inventory_item"
	},
	"untill.option_article_spec_price": {
		"id_option_article_prices": "untill.option_article_prices",
		"id_special_words": "untill.special_words"
	},
	"untill.size_modifier_item": {
		"id_size_modifier": "untill.size_modifier"
	},
	"untill.ks_wf_stage_template": {},
	"untill.waiter_positions": {},
	"untill.menu_screens": {
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.suppliers": {
		"id_countries": "untill.countries",
		"id_currency": "untill.currency"
	},
	"untill.extra_field_values": {},
	"untill.cash_declaration": {
		"id_untill_users": "untill.untill_users"
	},
	"untill.client_discount_groups": {
		"id_clients": "untill.clients",
		"id_accounts": "untill.accounts",
		"id_discount_groups": "untill.discount_groups"
	},
	"untill.article_position_ex": {
		"id_articles": "untill.articles",
		"id_sales_area": "untill.sales_area",
		"id_department": "untill.department"
	},
	"untill.printers": {
		"id_printer_drivers": "untill.printer_drivers",
		"id_ordermans": "untill.ordermans",
		"id_falcon_terminals": "untill.falcon_terminals",
		"id_computers": "untill.computers"
	},
	"untill.recipe": {
		"id_unity_produced": "untill.unity",
		"id_food_group": "untill.food_group"
	},
	"untill.order_item_extra": {
		"id_order_item": "untill.order_item",
		"id_menu_item": "untill.menu_item",
		"id_pbill_item": "untill.pbill_item",
		"id_article_barcodes": "untill.article_barcodes"
	},
	"untill.department": {
		"id_options_condiment": "untill.options",
		"id_age_groups": "untill.age_groups",
		"id_food_group": "untill.food_group",
		"id_options_supplement": "untill.options"
	},
	"untill.payments_hash": {
		"id_payments": "untill.pbill_payments",
		"id_untill_users": "untill.untill_users"
	},
	"untill.stock_open_day_item": {
		"id_inventory_item": "untill.inventory_item",
		"id_stocking_locations": "untill.stocking_locations",
		"id_stock_open_day": "untill.stock_open_day"
	},
	"untill.prepaid_groups_articles": {
		"id_articles": "untill.articles",
		"id_prepaid_groups": "untill.prepaid_groups"
	},
	"untill.inventory_par": {
		"id_periods": "untill.periods",
		"id_inventory_item": "untill.inventory_item"
	},
	"untill_user_fingerprints": {
		"id_untill_users": "untill.untill_users"
	},
	"untill.pbill_payments": {
		"id_driver_discount": "untill.driver_discount",
		"id_pbill": "untill.pbill",
		"id_payments": "untill.payments"
	},
	"untill.order_item_stock_price": {
		"id_order_item": "untill.order_item"
	},
	"untill.computers": {
		"id_screen_groups": "untill.screen_groups",
		"id_tickets_clock": "untill.tickets",
		"id_cash_tickets": "untill.tickets"
	},
	"untill.stock_cost_correction": {
		"id_untill_users": "untill.untill_users",
		"id_stock_locations": "untill.stocking_locations",
		"id_conduct_untill_user": "untill.untill_users",
		"id_inventory_item": "untill.inventory_item"
	},
	"untill.pua_groups": {},
	"untill.untill_group_users": {},
	"untill.cal_orders": {
		"id_callers": "untill.callers",
		"id_users_open": "untill.untill_users",
		"id_users_close": "untill.untill_users",
		"id_orders": "untill.orders"
	},
	"untill.discount_reasons": {
		"id_bookkp": "untill.bookkeeping"
	},
	"untill.table_range": {
		"id_table_area": "untill.table_area"
	},
	"untill.dep_button_setting": {
		"id_department": "untill.department",
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.customer_emails": {
		"id_clients": "untill.clients"
	},
	"untill.order_item_bookp": {
		"id_order_item": "untill.order_item",
		"id_bookkeeping_turnover": "untill.bookkeeping",
		"id_bookkeeping_vat": "untill.bookkeeping"
	},
	"untill.func_panel_tabs": {
		"id_payments": "untill.payments"
	},
	"untill.restaurant_falcons": {
		"id_preparation_area": "untill.preparation_area",
		"id_ks": "untill.kitchen_screens",
		"id_ksc": "untill.kitchen_screen_counters",
		"id_falcon_terminals": "untill.falcon_terminals",
		"id_printers_bill": "untill.printers",
		"id_tickets_bill": "untill.tickets"
	},
	"untill.pbill_hash": {
		"id_pbill_item": "untill.pbill_item",
		"id_untill_users": "untill.untill_users"
	},
	"untill.stock_open_day": {},
	"untill.bonus_groups_articles": {
		"id_bonus_groups": "untill.bonus_groups",
		"id_articles": "untill.articles"
	},
	"untill.kitchen_screens_link": {
		"id_ks_to": "untill.kitchen_screens",
		"id_ks_from": "untill.kitchen_screens"
	},
	"untill.article_notify": {
		"id_preparation_area": "untill.preparation_area",
		"id_articles": "untill.articles"
	},
	"untill.stock_adjustment_item": {
		"id_inventory_item": "untill.inventory_item",
		"id_stock_adjustment": "untill.stock_adjustment"
	},
	"untill.articles_periods": {
		"id_articles": "untill.articles",
		"id_periods": "untill.periods"
	},
	"untill.olap_db_sers": {},
	"untill.rent_periods_articles": {
		"id_articles": "untill.articles",
		"id_rent_period_items": "untill.rent_period_items"
	},
	"untill.neg_orders": {
		"id_orders": "untill.orders",
		"id_discount_reasons": "untill.discount_reasons",
		"id_manager": "untill.untill_users"
	},
	"untill.export_targets": {},
	"untill.option_tree": {
		"id_options_parent": "untill.options",
		"id_options_child": "untill.options"
	},
	"untill.screen_images": {},
	"untill.future_bills": {
		"id_untill_users": "untill.untill_users",
		"id_clients": "untill.clients"
	},
	"untill.articles": {
		"id_size_modifier": "untill.size_modifier",
		"id_packing": "untill.packing",
		"id_recipe": "untill.recipe",
		"id_beco_group": "untill.beco_groups",
		"id_pua_groups": "untill.pua_groups",
		"id_age_groups": "untill.age_groups",
		"id_ksc": "untill.kitchen_screen_counters",
		"id_currency": "untill.currency",
		"id_promotions": "untill.promotions",
		"id_food_group": "untill.food_group",
		"id_free_option": "untill.options",
		"id_suppliers": "untill.suppliers",
		"id_ks_wf": "untill.ks_wf_template",
		"id_rent_periods": "untill.rent_periods",
		"id_beco_location": "untill.beco_locations",
		"id_rental_group": "untill.rental_group",
		"id_departament": "untill.department",
		"id_courses": "untill.courses",
		"id_commission": "untill.commission",
		"id_vd_group": "untill.vd_groups",
		"id_inventory_item": "untill.inventory_item",
		"id_unity_sales": "untill.unity_conversion",
		"id_article_ksp": "untill.kitchen_screen_purposes",
		"id_extra_field_values": "untill.extra_field_values"
	},
	"untill.article_options": {
		"id_options": "untill.options",
		"id_articles": "untill.articles",
		"id_courses": "untill.courses"
	},
	"untill.eft_config_selections": {
		"id_payments": "untill.payments"
	},
	"untill.tickets": {},
	"untill.order_item_onhold": {
		"id_order_item": "untill.order_item"
	},
	"untill.size_modifier": {},
	"untill.computer_devices": {
		"id_computers": "untill.computers"
	},
	"untill.options": {},
	"untill.discount_groups": {
		"id_discount_reasons": "untill.discount_reasons"
	},
	"untill.periodical_reports": {
		"id_tickets": "untill.tickets"
	},
	"untill.printers_mapping": {
		"id_from_printer": "untill.printers",
		"id_to_printer": "untill.printers"
	},
	"untill.computer_drawers": {
		"id_drawers": "untill.printers",
		"id_computers": "untill.computers"
	},
	"untill.pbill_hotel_payments_info": {
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.settings": {
		"id_bookkp_vat": "untill.bookkeeping",
		"id_bookkp_paymentk": "untill.bookkeeping",
		"id_bookkp_costcor": "untill.bookkeeping",
		"id_bookkp_physvar": "untill.bookkeeping",
		"id_bookkp_turnover": "untill.bookkeeping",
		"id_bookkp_target": "untill.export_targets",
		"id_bookkp_cos": "untill.bookkeeping",
		"id_bookkp_stockrcvd": "untill.bookkeeping",
		"id_bookkp_writeoff": "untill.bookkeeping",
		"id_bookkp_inventory": "untill.bookkeeping",
		"id_holiday": "untill.periods",
		"id_bookkp_payment": "untill.bookkeeping",
		"id_msglayout": "untill.tickets",
		"id_bookkp_turnoverk": "untill.bookkeeping",
		"id_bookkp_vatk": "untill.bookkeeping"
	},
	"untill.pbill_return": {
		"id_void_reason": "untill.discount_reasons",
		"id_pbill": "untill.pbill"
	},
	"untill.supplier_item": {
		"id_inventory_item": "untill.inventory_item",
		"id_unity_purchase": "untill.unity_conversion",
		"id_suppliers": "untill.suppliers"
	},
	"untill.voided_items": {
		"id_order_item": "untill.order_item",
		"id_void_reason": "untill.discount_reasons",
		"id_untill_users": "untill.untill_users"
	},
	"untill.order_item_newyse_data": {
		"id_order_item": "untill.order_item",
		"id_prepaid_groups": "untill.prepaid_groups"
	},
	"untill.kitchen_screen_counters": {
		"id_pu_printers": "untill.printers",
		"id_pu_tickets": "untill.tickets"
	},
	"untill.pbill_email": {
		"id_pbill": "untill.pbill"
	},
	"untill.option_sales_area": {
		"id_options": "untill.options",
		"id_sales_area": "untill.sales_area"
	},
	"untill.pbill_item_bookp": {
		"id_pbill_item": "untill.pbill_item",
		"id_bookkeeping_turnover": "untill.bookkeeping",
		"id_bookkeeping_vat": "untill.bookkeeping"
	},
	"untill.inventory_categories": {
		"id_count_frequency": "untill.count_frequencies"
	},
	"untill.stock_invoice_item": {
		"id_inventory_item": "untill.inventory_item",
		"id_supplier_item": "untill.supplier_item",
		"id_stock_invoice": "untill.stock_invoice"
	},
	"untill.vd_aliases": {},
	"untill.rent_units": {
		"id_articles": "untill.articles"
	},
	"untill.pa_ks_notify": {
		"id_preparation_area": "untill.preparation_area",
		"id_ks": "untill.kitchen_screens"
	},
	"untill.food_group": {
		"id_bookkp_turnover": "untill.bookkeeping",
		"id_bookkp_vat": "untill.bookkeeping",
		"id_category": "untill.category",
		"id_bookkp_vat_sec": "untill.bookkeeping"
	},
	"untill.rental_group": {},
	"untill.beco_article_locations": {
		"id_articles": "untill.articles",
		"id_locations": "untill.beco_locations"
	},
	"untill.rent_repair_reasons": {},
	"untill.cash_declaration_items": {
		"id_cash_declaration": "untill.cash_declaration",
		"id_currency_notes_coins": "currency_notes_coins"
	},
	"untill.olap_db": {},
	"untill.voucher_payments": {
		"id_vouchers": "untill.vouchers",
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.article_sm_price_periods": {
		"id_article_price_periods": "untill.article_price_periods",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.global_scripts": {},
	"untill.courses": {
		"id_ks_ticket": "untill.tickets",
		"id_ks_printer": "untill.printers",
		"id_pu_printer": "untill.printers",
		"id_pu_ticket": "untill.tickets"
	},
	"untill.article_discount": {
		"id_articles": "untill.articles",
		"id_currency": "untill.currency"
	},
	"untill.order_item_newyse_prices": {
		"id_order_item": "untill.order_item"
	},
	"untill.ordermans": {
		"id_menu": "untill.menu_screens",
		"id_screen_groups": "untill.screen_groups",
		"id_computers": "untill.computers",
		"id_start_screen": "untill.order_screens"
	},
	"untill.bonus_groups": {},
	"untill.rent_periods": {},
	"untill.department_available": {
		"id_sales_area": "untill.sales_area",
		"id_department": "untill.department"
	},
	"untill.func_panel_settings": {},
	"untill.article_size_modifier_price": {
		"id_article_prices": "untill.article_prices",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.tpapi_tokens": {},
	"untill.purchase_order_item": {
		"id_purchase_order": "untill.purchase_order",
		"id_inventory_item": "untill.inventory_item",
		"id_supplier_item": "untill.supplier_item"
	},
	"untill.bill_reprints": {
		"id_pbill": "untill.pbill",
		"id_untill_users": "untill.untill_users"
	},
	"untill.orders_newyse_data": {
		"id_orders": "untill.orders"
	},
	"untill.discounts": {
		"id_category": "untill.category",
		"id_discount_reasons": "untill.discount_reasons",
		"id_periods": "untill.periods",
		"id_department": "untill.department",
		"id_courses": "untill.courses",
		"id_food_group": "untill.food_group"
	},
	"untill.article_prices": {
		"id_prices": "untill.prices",
		"id_currency": "untill.currency",
		"id_articles": "untill.articles"
	},
	"untill.notes_coins": {},
	"untill.ug_report_groups": {
		"id_ug": "untill.untill_group_users",
		"id_report_groups": "untill.report_groups"
	},
	"untill.printer_drivers": {},
	"untill.default_entities": {},
	"untill.purchase_order": {
		"id_conduct_untill_user": "untill.untill_users",
		"id_suppliers": "untill.suppliers",
		"id_untill_users": "untill.untill_users"
	},
	"untill.deposit_card_payments_info": {
		"id_deposits": "untill.account_deposits",
		"id_vouchers": "untill.vouchers"
	},
	"untill.wm_tasks": {},
	"untill.order_item_sizes": {
		"id_order_item": "untill.order_item",
		"id_menu_item": "untill.menu_item",
		"id_pbill_item": "untill.pbill_item",
		"id_articles": "untill.articles",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.period_values": {
		"id_periods": "untill.periods"
	},
	"untill.article_available": {
		"id_sales_area": "untill.sales_area",
		"id_periods": "untill.periods",
		"id_articles": "untill.articles"
	},
	"untill.pbill_item_refund": {
		"id_untill_users": "untill.untill_users",
		"id_courses": "untill.courses",
		"id_menu": "untill.menus",
		"id_pbill": "untill.pbill",
		"id_articles": "untill.articles",
		"id_department": "untill.department",
		"id_food_group": "untill.food_group",
		"id_category": "untill.category",
		"id_prices": "untill.prices"
	},
	"untill.extra_fields": {},
	"untill.bonus_items": {
		"id_article_bonus_groups": "untill.bonus_groups",
		"id_parent_menu_item": "untill.menu_item",
		"id_parent_bonus_article": "untill.articles",
		"id_order_item": "untill.order_item",
		"id_parent_item": "untill.order_item"
	},
	"untill.article_button_setting": {
		"id_articles": "untill.articles",
		"id_screen_groups": "untill.screen_groups"
	},
	"untill.payment_bookkeeping": {
		"id_payments": "untill.payments",
		"id_bookkeeping": "untill.bookkeeping"
	},
	"untill.ticket_logos": {},
	"untill.stock_cost_correction_item": {
		"id_stock_cost_correction": "untill.stock_cost_correction",
		"id_stock_invoice_item": "untill.stock_invoice_item"
	},
	"untill.zip_codes": {},
	"untill.sync_db_sers": {},
	"untill.bars": {},
	"untill.inventory_item_locations": {
		"id_inventory_item": "untill.inventory_item",
		"id_stocking_locations": "untill.stocking_locations",
		"id_unity_counting": "untill.unity_conversion"
	},
	"untill.bo_sc_items": {
		"id_department": "untill.department",
		"id_food_group": "untill.food_group",
		"id_bsc": "untill.bo_service_charge",
		"id_category": "untill.category"
	},
	"untill.pbill_balance": {
		"id_pbill": "untill.pbill",
		"id_clients": "untill.clients",
		"id_accounts": "untill.accounts"
	},
	"untill.user_updates": {
		"id_untill_users": "untill.untill_users",
		"id_update_user": "untill.untill_users"
	},
	"untill.suppliers_contacts": {
		"id_suppliers": "untill.suppliers"
	},
	"untill.t2o_members": {
		"id_t2o_groups": "untill.t2o_groups",
		"id_clients": "untill.clients",
		"id_users_join": "untill.untill_users",
		"id_users_quit": "untill.untill_users"
	},
	"untill.account_payment_data": {
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.eft_config_sel_avail": {
		"id_falcon_terminals": "untill.falcon_terminals",
		"id_ordermans": "untill.ordermans",
		"id_eft_config_selections": "untill.eft_config_selections",
		"id_computers": "untill.computers"
	},
	"untill.complete_meal": {
		"id_pbill": "untill.pbill",
		"id_untill_users": "untill.untill_users"
	},
	"untill.pbill_payer": {
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.extra_field_items": {
		"id_extra_field_values": "untill.extra_field_values",
		"id_extra_field_defs": "untill.extra_field_defs"
	},
	"untill.smartcards_turnover": {
		"id_untill_users": "untill.untill_users",
		"id_smartcards": "untill.smartcards",
		"id_pbill_payments": "untill.pbill_payments",
		"id_payments": "untill.payments",
		"id_deposit_bookkeeping": "untill.bookkeeping"
	},
	"untill.func_panel_tab_buttons": {
		"id_func_panel_tabs": "untill.func_panel_tabs",
		"id_payments": "untill.payments"
	},
	"untill.articles_allergens": {
		"id_allergens": "untill.allergens",
		"id_articles": "untill.articles"
	},
	"untill.order_item": {
		"id_article_options": "untill.article_options",
		"id_size_modifier_item": "untill.size_modifier_item",
		"id_orders": "untill.orders",
		"id_articles": "untill.articles",
		"id_prices": "untill.prices",
		"id_menu": "untill.menus",
		"id_courses": "untill.courses",
		"id_option_article": "untill.option_article",
		"id_smartcards": "untill.smartcards"
	},
	"untill.componoud_device_drivers": {
		"id_computer_devices": "untill.computer_devices"
	},
	"untill.inv_loc_period_normal": {
		"id_periods": "untill.periods",
		"id_inventory_item_locations": "untill.inventory_item_locations"
	},
	"untill.smartcardordergroups": {
		"id_smartcards": "untill.smartcard_groups"
	},
	"untill.bg_sm_prices": {
		"id_bg_articles_prices": "untill.bonus_groups_articles_prices",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.smartcards": {
		"id_smartcard_groups": "untill.smartcard_groups",
		"id_clients": "untill.clients"
	},
	"untill.ingredient_suppliers": {
		"id_suppliers": "untill.suppliers",
		"id_ingredients": "untill.ingredients"
	},
	"untill.waiter_table_area": {
		"id_table_area": "untill.table_area",
		"id_waiters": "untill.waiters"
	},
	"untill.unity_conversion": {
		"id_unity": "untill.unity",
		"id_unity_convert": "untill.unity"
	},
	"untill.pua_groups_sales_area": {
		"id_pua_groups": "untill.pua_groups",
		"id_sales_area": "untill.sales_area"
	},
	"untill.report_groups": {},
	"untill.payments": {
		"id_bookkp": "untill.bookkeeping",
		"id_currency": "untill.currency"
	},
	"untill.stock_units": {},
	"untill.moved_tables": {
		"id_untill_users": "untill.untill_users",
		"id_screen_group": "untill.screen_groups"
	},
	"untill.order_item_allergens": {
		"id_order_item": "untill.order_item",
		"id_menu_item": "untill.menu_item",
		"id_allergens": "untill.allergens",
		"id_pbill_item": "untill.pbill_item"
	},
	"untill.table_printer": {
		"id_stock_locations": "untill.stocking_locations",
		"id_ksc": "untill.kitchen_screen_counters",
		"id_printers": "untill.printers",
		"id_tickets": "untill.tickets",
		"id_table_area": "untill.table_area",
		"id_preparation_area": "untill.preparation_area"
	},
	"untill.unity": {},
	"untill.sync_db_sers_p": {},
	"untill.vd_receipts": {
		"id_article": "untill.articles",
		"id_receipt_article": "untill.articles"
	},
	"untill.func_payment_buttons": {},
	"untill.prices": {},
	"untill.promotions": {},
	"untill.ingredients": {
		"id_unity_purchase": "untill.unity",
		"id_unity_sales": "untill.unity",
		"id_currency": "untill.currency"
	},
	"untill.restaurant_computers": {
		"id_psp_layout": "untill.tickets",
		"id_rear_disp_printer": "untill.printers",
		"id_init_ksc": "untill.kitchen_screen_counters",
		"id_tickets_fiscal_footer": "untill.tickets",
		"id_ta_total_layout": "untill.tickets",
		"id_printers_proforma": "untill.printers",
		"id_rear_disp_article_layout": "untill.tickets",
		"id_beco_location": "untill.beco_locations",
		"id_tickets_order_journal": "untill.tickets",
		"id_ticket_voucher_bunch": "untill.tickets",
		"id_tickets_bill": "untill.tickets",
		"id_tickets_journal": "untill.tickets",
		"id_tickets_taorder": "untill.tickets",
		"id_second_article_layout": "untill.tickets",
		"id_printers_void": "untill.printers",
		"id_tickets_proforma": "untill.tickets",
		"id_tickets_control_journal": "untill.tickets",
		"id_printers_taorder": "untill.printers",
		"id_rear_disp_bill_layout": "untill.tickets",
		"id_oif_preparation_area": "untill.preparation_area",
		"id_tickets_void": "untill.tickets",
		"id_screens_order": "untill.screens",
		"id_printers_giftcards": "untill.printers",
		"id_journal_printer": "untill.printers",
		"id_return_layout": "untill.tickets",
		"id_tickets_voucher": "untill.tickets",
		"id_email_invoice_layout": "untill.tickets",
		"id_ticket_voucher_bill": "untill.tickets",
		"id_sales_area": "untill.sales_area",
		"id_rent_printer": "untill.printers",
		"id_reprint_order": "untill.tickets",
		"id_screens_part": "untill.screens",
		"id_inout_layout": "untill.tickets",
		"id_inout_printer": "untill.printers",
		"id_coupon_layout": "untill.tickets",
		"id_screens_payment": "untill.screens",
		"id_rear_screen_saver": "untill.tickets",
		"id_tickets_giftcards": "untill.tickets",
		"id_tickets_manager": "untill.tickets",
		"id_stock_location": "untill.stocking_locations",
		"id_drawer_layout": "untill.tickets",
		"id_printers_voucher": "untill.printers",
		"id_screens_condiment": "untill.screens",
		"id_deposit_layout": "untill.tickets",
		"id_deposit_printer": "untill.printers",
		"id_printers_1": "untill.printers",
		"id_periods": "untill.periods",
		"id_invoice_layout": "untill.tickets",
		"id_computers": "untill.computers",
		"id_init_ks": "untill.kitchen_screens",
		"id_stock_printer": "untill.printers",
		"id_tickets_preauth": "untill.tickets",
		"id_screens_supplement": "untill.screens",
		"id_rent_layout": "untill.tickets",
		"id_printers_manager": "untill.printers",
		"id_tickets_reopen": "untill.tickets",
		"id_printers_reopen": "untill.printers",
		"id_tickets_prof_fiscal_footer": "untill.tickets"
	},
	"untill.pbill": {
		"id_real_untill_user": "untill.untill_users",
		"id_untill_users": "untill.untill_users",
		"id_sales_area": "untill.sales_area",
		"id_clients": "untill.clients",
		"id_currency": "untill.currency"
	},
	"untill.account_deposits": {
		"id_untill_users": "untill.untill_users",
		"id_clients": "untill.clients",
		"id_payments": "untill.payments",
		"id_sales_area": "untill.sales_area",
		"id_bookkeeping": "untill.bookkeeping"
	},
	"untill.abg_sm_prices": {
		"id_article_bonus_prices": "untill.article_bonus_prices",
		"id_size_modifier_item": "untill.size_modifier_item"
	},
	"untill.category": {},
	"untill.sales_area_exceptions": {
		"id_periods": "untill.periods",
		"id_prices": "untill.prices",
		"id_sales_area": "untill.sales_area"
	},
	"untill.t2o_groups": {
		"id_clients": "untill.clients",
		"id_users_created": "untill.untill_users",
		"id_users_closed": "untill.untill_users"
	},
	"untill.beco_locations": {},
	"untill.computer_users": {
		"id_computers": "untill.computers",
		"id_untill_users": "untill.untill_users"
	},
	"untill.table_area_ks": {
		"id_table_area": "untill.table_area",
		"id_ks_from": "untill.kitchen_screens",
		"id_ks_to": "untill.kitchen_screens",
		"id_periods": "untill.periods"
	},
	"untill.system_vars": {},
	"untill.cancelled_task_recipients": {
		"id_db_tasks_recipients": "untill.db_tasks_recipients"
	},
	"untill.order_type": {},
	"untill.bill": {
		"id_user_proforma": "untill.untill_users",
		"id_cardprice": "untill.prices",
		"id_discount_reasons": "untill.discount_reasons",
		"id_untill_users": "untill.untill_users",
		"id_clients": "untill.clients",
		"id_courses": "untill.courses",
		"id_t2o_groups": "untill.t2o_groups",
		"id_order_type": "untill.order_type",
		"id_alter_user": "untill.untill_users",
		"id_time_article": "untill.articles",
		"id_bo_service_charge": "untill.bo_service_charge",
		"id_serving_time": "untill.serving_time",
		"id_callers_last": "untill.callers"
	},
	"untill.smartcard_tables": {
		"id_smartcards": "untill.smartcards"
	},
	"untill.client_smartcard_uids": {
		"id_clients": "untill.clients"
	},
	"untill.kitchen_screens_substations": {
		"id_ks_sub": "untill.kitchen_screens",
		"id_ks_main": "untill.kitchen_screens"
	},
	"untill.menu_item": {
		"id_options": "untill.options",
		"id_option_article": "untill.option_article",
		"id_size_modifier_item": "untill.size_modifier_item",
		"id_article_options": "untill.article_options",
		"id_articles": "untill.articles",
		"id_prices": "untill.prices",
		"id_courses": "untill.courses",
		"id_menu": "untill.menus"
	},
	"untill.menu_item_newyse_data": {
		"id_menu_item": "untill.menu_item",
		"id_prepaid_groups": "untill.prepaid_groups"
	},
	"untill.menu_item_bookp": {
		"id_bookkeeping_turnover": "untill.bookkeeping",
		"id_bookkeeping_vat": "untill.bookkeeping",
		"id_menu_item": "untill.menu_item"
	},
	"untill.menu_item_newyse_prices": {
		"id_menu_item": "untill.menu_item"
	},
	"untill.menus": {},
	"untill.smartcard_table_cards": {
		"id_smartcards": "untill.smartcards",
		"id_smartcard_tables": "untill.smartcard_tables"
	},
	"untill.apostill_hddcodes": {
		"id_dealers": "untill.dealers"
	},
	"untill.client_cards": {
		"id_clients": "untill.clients",
		"id_client_cards_name": "untill.client_card_names"
	},
	"untill.dealers": {
		"id_clients": "untill.clients",
		"id_banks": "untill.banks"
	},
	"untill.pbill_cashm_payments_info": {
		"id_pbill_payments": "untill.pbill_payments"
	},
	"untill.client_card_names": {},
	"untill.banks": {
		"id_currency": "untill.currency",
		"id_order_layout": "untill.tickets"
	},
	"untill.licenses": {
		"id_dealers": "untill.dealers",
		"id_licenses_prev": "untill.licenses",
		"id_bill": "untill.bill"
	},
	"untill.serving_time": {},
	"untill.art_free_opt_defaults": {
		"id_articles_free_options": "untill.articles_free_options",
		"id_option_article": "untill.option_article"
	},
	"untill.dep_position_ex": {
		"id_sales_area": "untill.sales_area",
		"id_department": "untill.department"
	},
	"untill.licenses_online": {
		"id_licenses": "untill.licenses"
	},
	"untill.kitchen_screen_alert_periods": {
		"id_kitchen_screens": "untill.kitchen_screens",
		"id_periods": "untill.periods"
	},
	"untill.air_table_plan": {},
	"untill.air_table_plan_item": {
		"id_air_table_plan": "untill.air_table_plan"
	},
	"untill.air_article_messages": {}
};

export default ForeignKeys;