/*
 * Copyright (c) 2020-present unTill Pro, Ltd.
 */

import * as Helpers from '../../src/classes/helpers'; 

test('Helpers.bufferToLangMap test #1', () => {
    const base64str = "CQAAAAQAAAAwADAAMAAwAAsAAABTAHQAaQBsAGwAIABXAGEAdABlAHIABAAAADAANAAwADYACQAAAFAAbwBzAHQAZQB2AGEAbgBkAAQAAAAwADQAMAA3ABcAAABXAGEAcwBzAGUAcgAgAG8AaABuAGUAIABLAG8AaABsAGUAbgBzAOQAdQByAGUABAAAADAANAAwAEEACgAAAFAAbABhAG4AbwAgAEEAZwB1AGEABAAAADAANAAwAEMACAAAAEUAYQB1ACAAUABsAGEAdAAEAAAAMAA0ADEAMAAPAAAAQQBjAHEAdQBhACAAIABuAGEAdAB1AHIAYQBsAGUABAAAADAANAAxADUAEAAAAE4AaQBlAGcAYQB6AG8AdwBhAG4AYQAgAHcAbwBkAGEABAAAADAANAAxAEQABgAAAFYAYQB0AHQAZQBuAAQAAAAwADgAMQAzAAkAAABTAHAAYQAgAEIAbABhAHUAdwA=";

    let map = Helpers.bufferToLangMap(base64str);
    let res = Helpers.langMapToBuffer(map);

    expect(base64str).toEqual(res);
});